version: "3"

services:
  flask_app:
    container_name: "admon_boletos"
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
  db:
    image: mysql:8.0.31
    restart: always
    container_name: db
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eventos_db
    