"""add_column_to_ticket_table

Revision ID: 947e2958bf3f
Revises: 38b1d78c8c7b
Create Date: 2023-01-13 10:34:18.181325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '947e2958bf3f'
down_revision = '38b1d78c8c7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('client_last_name', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('client_last_name')
        batch_op.drop_column('client_name')

    # ### end Alembic commands ###
